### PR TITLE
Import/Export of xlsx files

### PR DESCRIPTION
**Pull request by kown7**
This commit adds an output option to generate an xlsx file (with a template if so desired). This file can be edited an re-imported.

A working example can be found [here](https://github.com/kown7/rmtoo-example). This could eventually be included as submodule.

### CODE REVIEW

**Comment by florath** [comment]
Hello!

I really like the idea of import and export xlsx files. Thank you very much for your work.,

The problem is, that I don't have the resources to review 62 commits - where some of them are only patches to new code (???) [1].
Could you please split them up in logical blocks like
 * Import
 * Export
 * Generic things (like [2])
and file a pull request for each of them?

Could you please condense each of the pull requests in one commit? I really don't want to retrace the complete development process - but want to look only at the result.

Kind regards

Andre


[1] https://github.com/florath/rmtoo/pull/23/commits/e9349df8ba0910a73e7cca77c61dc9a710a7593d
[2] https://github.com/florath/rmtoo/pull/23/commits/3cb80359719905602edd9d91855d0477b20f0ca4

**Comment by kown7** [comment]
I'll try to to separate the pull request from all the other little things I've done.

Can we keep the Import/Export together as they've been co-developed in one `git merge --squash xls`?

**Comment by kown7** [comment]
This is now both Import and Export of xlsx files (given #30 has been merged).

This has been developed simultaneously because exporting and re-importing mustn't change the state of the req and toc files.

**Comment by kown7** [comment]
Finally, just two commits left.

**Pull request closed without merging**
